### ISSUE TITLE
Follow Sym-Links

### ISSUE THREAD

**Issue by adambarnett52** [dundee/disk_usage_exporter#11]
Hi
we have some directories  that have sym-links in but the exporter see these are empty folders and does not calculate the size , Is there way to treat the links as real folders?

Thanks
Adam

**Comment by dundee** [comment]
Not yet, but I will be simple to add this.

**Comment by adambarnett52** [comment]
Hi @dundee 
That would be great 
thanks

**Comment by adambarnett52** [comment]
Hi, Will 4940697 follow sym-link direcotires to calculate , i.e 

`/home/blah -> /link to another place/`

**Comment by dundee** [comment]
No, directory symlinks are not followed right now.

**Comment by adambarnett52** [comment]
Can the code be tweaked to allow it ?Sent from my iPhoneOn 12 Apr 2023, at 17:53, Daniel Milde ***@***.***> wrote:﻿
No, directory symlinks are not followed right now.
