### ISSUE TITLE
Metrics of non-existent folders

### ISSUE THREAD

**Issue by Maisia** [dundee/disk_usage_exporter#12]
Hello. 
I faced the following issue and hope you'll be able to give some advice about it.
I use disk_usage_exporter to monitor disk usage of databases inside mysql instance. Recently I noticed that exporter shows old data.

Disk_usage_exporter runs as additional container of mysql pod:
```
  disk-exporter:
    Image:         ghcr.io/dundee/disk_usage_exporter/disk_usage_exporter-c4084307c537335c2ddb6f4b9b527422:latest
    Image ID:      docker-pullable://ghcr.io/dundee/disk_usage_exporter/disk_usage_exporter-c4084307c537335c2ddb6f4b9b527422@sha256:320b9e61b93ce4d339de9b9462fbcad862710f8a6884bd62ba631a9055eecb27
    Port:          9995/TCP
    Host Port:     0/TCP
    Args:
      -l=1
      -p=/var/lib/mysql
    State:          Running
      Started:      Sat, 31 Dec 2022 13:30:50 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  384Mi
    Requests:
      cpu:        100m
      memory:     256Mi
    Environment:  <none>
    Mounts:
      /var/lib/mysql from data (rw)
```
There are folders that are not present in pod itself as they were removed long time ago, for example:
```
sh-4.2$ ls -lah /var/lib/mysql/old_database
ls: cannot access /var/lib/mysql/old_database: No such file or directory
sh-4.2$ ls -lah /var/lib/mysql/xtrabackup_logfile
ls: cannot access /var/lib/mysql/xtrabackup_logfile: No such file or directory
```
However I still can see those folders metrics in browser at http://127.0.0.1:8080/metrics:
```
node_disk_usage_bytes{path="/var/lib/mysql/old_database"} 1.3676023808e+10
node_disk_usage_bytes{path="/var/lib/mysql/xtrabackup_logfile"} 7.314219008e+09
```
And in general from endpoint I get much more metrics than currently existing folders/files. Disk_usage_exporter returns not only current folders/files, but also all folders/files that ever existed at monitored path.
My expectation was that disk_usage_exporter provides data only for existing folders/files.

Is the output with all ever existed data is expected? If there any cache within disk_usage_exporter that holds old data can it be cleared?

**Comment by dundee** [comment]
I think this is expected behaviour. Prometheus exporter has no clue if the provided data was already consumed by all the scrapers or not, so it provides all data it has.

**Comment by dundee** [comment]
If you want to purge the data over some time, you can schedule a restart of the exporter.

**Comment by Maisia** [comment]
Hello @dundee. Thank you for the clarification.
