### ISSUE TITLE
It cannot be run on CentOS.

### ISSUE THREAD

**Issue by EnergeticWong** [dundee/disk_usage_exporter#17]
package name：disk_usage_exporter_linux_amd64.tgz

```
 [root@localhost opt]# tar -zxvf disk_usage_exporter_linux_amd64.tgz -C diskusage/
._disk_usage_exporter_linux_amd64
tar: Ignoring unknown extended header keyword `LIBARCHIVE.xattr.com.apple.provenance'
disk_usage_exporter_linux_amd64
```
`[root@localhost diskusage]# file disk_usage_exporter_linux_amd64 

disk_usage_exporter_linux_amd64: Mach-O 64-bit executable
 `

How can I run it on CentOS? Please advise.

**Comment by dundee** [comment]
Oh, my mistake. I will replace the file in a while.

**Comment by dundee** [comment]
Please try to download the file again now. Should be fixed.
