### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by TinJoy59** [dundee/disk_usage_exporter#6]
Hello,
Is it possible to package this exporter as a docker image? I have Grafana, Prometheus and various other exporters running as docker containers.  believe many others are doing the same.

As I'm still learning Linux, I can't even begin to understand how to install this standalone.

**Comment by dundee** [comment]
Hello,
it would not make much sense since Docker container sees different filesystem, so the exporter would report disk usage statistics about the volume mounted to docker which is not very useful.

**Comment by TinJoy59** [comment]
After some digging, it turns out that [someone forked](https://github.com/neredera/disk_usage_exporter) this repo and added Docker support. 

I just mounted the folders I need to monitor as persistent volumes in the container with read-only access. I blacklisted all root sub-directories, leaving only the ones I have mounted from outside the container. 

It works perfectly.
