### ISSUE TITLE
Multi "analyzed-path" with customatisable "dir-level"

### ISSUE THREAD

**Issue by bbmh23** [dundee/disk_usage_exporter#8]
Hi @dundee !
I suggest you an improvement in order to monitor different repository with customisable "dir-level".
The goal of the suggestion is to evaluate several targeted repository while consuming the least system resources as possible.
Regards,
Bruno

**Comment by ericashi** [comment]
Hi @dundee ,

I am using Version 0.4.0 and I did not see this capability yet.
May I know if this enhancement is already in the latest release please?
May I know which version has this feature or when will it be release, please.

Thank you.

Best Regards,
Erica Ooi

**Comment by MikeyCarter** [comment]
Got another vote on this.   

The /var/cache/yum directory grows on me but sometimes it's not that it's the /var/cache/fscache or something else.   Trying to do post-analysis is difficult if I'm also getting all the noise from /tmp three levels deep.

Granted I realize we can do sum commands but that makes reports very complicated.

**Comment by dundee** [comment]
Added in `v0.5.0` 🎉
